#cs ----------------------------------------------------------------------------

 AutoIt Version: 3.3.14.2
 Author:         myName

 Script Function:
	Template AutoIt script.

#ce ----------------------------------------------------------------------------

; Script Start - Add your code below here
#include <MsgBoxConstants.au3>
Func kill()
   Exit 0
EndFunc

WinActivate("Bing - Google Chrome")
WinSetState("Bing - Google Chrome", " ",@SW_MAXIMIZE)
MouseMove(275,209,10)
MouseClick("left")
Send("0")
Send("{ENTER}")
Sleep(5000)
MouseMove(135,99,10)
MouseClick("left")
Send("01")
Send("{ENTER}")
Sleep(5000)
MouseClick("left")
Send("02")
Send("{ENTER}")
Sleep(5000)
MouseClick("left")
Send("03")
Send("{ENTER}")
Sleep(5000)
MouseClick("left")
Send("04")
Send("{ENTER}")
Sleep(5000)
MouseClick("left")
Send("05")
Send("{ENTER}")
Sleep(5000)
MouseClick("left")
Send("06")
Send("{ENTER}")
Sleep(5000)
MouseClick("left")
Send("07")
Send("{ENTER}")
Sleep(5000)
MouseClick("left")
Send("08")
Send("{ENTER}")
Sleep(5000)
MouseClick("left")
Send("09")
Send("{ENTER}")
Sleep(5000)
MouseClick("left")
Send("010")
Send("{ENTER}")
Sleep(5000)
MouseClick("left")
Send("011")
Send("{ENTER}")
Sleep(5000)
MouseClick("left")
Send("012")
Send("{ENTER}")
Sleep(5000)
MouseClick("left")
Send("013")
Send("{ENTER}")
Sleep(5000)
MouseClick("left")
Send("014")
Send("{ENTER}")
Sleep(5000)
MouseClick("left")
Send("015")
Send("{ENTER}")
Sleep(5000)
MouseClick("left")
Send("016")
Send("{ENTER}")
Sleep(5000)
MouseClick("left")
Send("017")
Send("{ENTER}")
Sleep(5000)
MouseClick("left")
Send("018")
Send("{ENTER}")
Sleep(5000)
MouseClick("left")
Send("019")
Send("{ENTER}")
Sleep(5000)
MouseClick("left")
Send("020")
Send("{ENTER}")
Sleep(5000)
MouseClick("left")
Send("021")
Send("{ENTER}")
Sleep(5000)
MouseClick("left")
Send("022")
Send("{ENTER}")
Sleep(5000)
MouseClick("left")
Send("023")
Send("{ENTER}")
Sleep(5000)
MouseClick("left")
Send("024")
Send("{ENTER}")
Sleep(5000)
MouseClick("left")
Send("025")
Send("{ENTER}")
Sleep(5000)
MouseClick("left")
Send("026")
Send("{ENTER}")
Sleep(5000)
MouseClick("left")
Send("027")
Send("{ENTER}")
Sleep(5000)
MouseClick("left")
Send("028")
Send("{ENTER}")
Sleep(5000)
MouseClick("left")
Send("029")
Send("{ENTER}")
Sleep(5000)
MouseClick("left")
Send("030")
Send("{ENTER}")
Sleep(5000)
MouseMove(225,47,10)
MouseClick("left")
Send("Bing.com")
Send("{ENTER}")
Sleep(10000)
MsgBox(1,"Google Bing Done", "Google Binger Made By Neeesh Has Finished Click Continue or Exit(This Will Automatically Close In 10 Seconds",10)

